config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :categories
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :activity_type, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :word

  has_many :results, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :name, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :category
  belongs_to :user

  has_many :results, dependent: :destroy
  has_many :words, through: :results
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :word
  belongs_to :user
  belongs_to :lesson
  belongs_to :answer
end

app/models/user.rb
class User < ApplicationRecord
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :activities, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :words, through: :results
  has_many :answers, through: :results

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@(?:[A-Z0-9-]+\.)+[A-Z]+\z/i

  validates :name, presence: true,
    length: {maximum: Settings.validates.username.maxium}
  validates :emails, presence: true,
    length: {maximum: Settings.validates.emails.maxium},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :password, presence: true,
    length: {minimum: Settings.validates.password.minium}

  has_secure_password

  before_save :email_downcase

  private

  def email_downcase
    self.emails = emails.downcase
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category

  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :lessons, through: :results
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :logged_in_user, except: [:new, :create, :show]
  before_action :find_activity

  def show; end

  private

  def find_activity
    @activity = current_user.activity.find_by id: params[:id]
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  attr_reader :user

  private

  def logged_in_user
    return if logged_in?
    flash[:danger] = t ".please-login"
    redirect_to login_url
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, except: [:index, :create]
  before_action :logged_in_user, only: [:create, :new, :destroy]

  def index
    @category = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "success"
      redirect_to categories_path
    else
      render :new
    end
  end

  def show;  end

  def edit; end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".success"
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = t ".success", category: @category.name
    redirect_to categories_url
  end

  private
  def find_category
    @category = Category.find_by id: params[:id]
  end

  def category_params
    params.require(:category).permit :name
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :logged_in_user, except: [:new, :create, :show]

  def index
    @lessons = current_user.lessons
  end

  def show; end

  def find_lesson
    @lesson = current_user.lessons.includes(results: [:answer, word: :answers]).
      find_by_id params[:id]
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :logged_in_user, except: [:new, :create, :show]
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_url if logged_in?
  end

  def create
    user = User.find_by emails: params[:session][:emails].downcase
    if user
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = t ".problem-login"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, except: [:new, :create, :show]
  def home
    if logged_in?
    	@activity  = current_user.activities.build
      @activities_item = current_user.activity.paginate page: params[:page]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:new, :create, :show]
  before_action :find_user, except: [:new, :index, :create]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate page: params[:page]
  end

  def new
    @user = User.new
  end

  def create
    user = User.new user_params
    if user.save
      log_in user
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @activity = user.activities.paginate(page: params[:page])
  end

  def edit; end

  def update
    if user.update_attributes user_params
      flash[:success] = t ".success"
      redirect_to user
    else
      render :edit
    end
  end

  def destroy
    user.destroy
    flash[:success] = t ".success", user: user.name
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit :name,
      :emails, :password, :password_confirmation
  end

  def logged_in_user
    return if logged_in?
    flash[:danger] = t ".warn"
    redirect_to login_url
  end

  def find_user
    user = User.find_by id: params[:id]
  end

  def correct_user
    return if @user.current_user? current_user
    redirect_to root_url
  end

  def admin_user
    return if current_user.admin?
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    page_title.empty? ? t(".title") : page_title + " | " + t("simple")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/helpers/user_helper.rb
module UsersHelper
  def gravatar_for user, size: 80
    gravatar_id = Digest::MD5.hexdigest user.emails.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: 80
    gravatar_id = Digest::MD5.hexdigest user.emails.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/activities/_activities.html.erb
<li id="activity-<%= activity.id %>">
  <%= link_to gravatar_for(activity.user, size: 50), activity.user %>
  <span class="user"><%= link_to activity.user.name, activity.user %></span>
  <span class="content"><%= activity.activity_type %></span>
  <span class="timestamp">
    at <%= time_ago_in_words(activity.created_at) %> ago.
  </span>
</li>

app/views/answers/show.html.erb
<%= form_for :person do |f| %>
  <%= f.check_box :content %><br />
<% end %>

app/views/categories/_category.html.erb
<div class="col-sm-4 col-md-4">
 <div class="thumbnail course">
    <%= image_tag placeholder_image(300) %>
    <div class="caption">
      <h3>
        <%= category.name %>
      </h3>
      <p>
        <%= link_to t(".let-start"), "#",
          class: "btn btn-success center-block", role: "button" %>
      </p>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row">
    <div class="category">
      <div class="form-style">
        <h1 class="text-center">
           <%= yield :tilte%>
        </h1>
        <div>
          <%= form_for @category do |f| %>
            <%= render "shared/error_messages", object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            <div class="button text-center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-lg" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<% provide :tilte, t(".tilte") %>
<% provide :button_text, t(".save") %>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<% provide :title, t(".tilte") %>

<% if current_user.admin? %>
  <div class="container category">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h1 class= "text-center">
          <%= t ".tilte" %>
        </h1>
        <table class="table table-bordered text-center table-cate">
          <%= link_to t(".new"), new_category_path,
            class: "btn btn-primary pull-right button"%>
          <thead>
            <tr>
              <th> <%= t ".name" %> </th>
              <th colspan="2" class="text-center">
                <%= t ".action" %>
              </th>
            </tr>
          </thead>

          <tbody>
            <% @category.each do |category| %>
              <tr >
                <td>
                  <%= category.name %>
                </td>
                <td class="text-center">
                  <%= link_to t(".edit"), edit_category_path(category),
                    class: "btn btn-primary action fa fa-edit" %>

                  <%= link_to t("delete"), category, method: :delete,
                     data: { confirm: t(".confirm") },
                      class: "btn btn-danger action fa fa-trash" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% else %>

  <div class="container catetogory">
    <h1 class="text-center cat-tilte">
      CATEGORY
    </h1>
    <div class="container cat-jumpotron">
      <div class="row">
        <%= render @categories %>
        <div class="paginate">
          <%= will_paginate @categories %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/categories/new.html.erb
<% provide :tilte, t(".tilte") %>
<% provide :button_text, t(".button_text") %>
<%= render "form", category: @category %>

app/views/lessons/_form_question.html.erb
<%= form_for :lesson do |f|%>
  <div class="panel-heading">
    <h3 class="panel-title">

    </h3>
  </div>
  <div class="panel-body btn btn-info">
    <%= f.fields_for :results do |result| %>
      <%= result.answers.each do |answers| %>
        <li>
          <label>
            <%= f.radio_button :answer_id, answers.id %>
            <%= answers.content %>
          </label>
        </li>
      <%end %>
    <% end %>
  </div>
<% end %>

app/views/lessons/show.html.erb
<h2>

</h2>
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-sm-offset-1">
      <%= render "form_question" %>
    </div>
  </div>
</div>