config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :categories
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :activity_type, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :word

  has_many :results, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :name, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :category
  belongs_to :user

  has_many :results, dependent: :destroy
  has_many :words, through: :results
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :word
  belongs_to :user
  belongs_to :lesson
  belongs_to :answer
end

app/models/user.rb
class User < ApplicationRecord
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :activities, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :words, through: :results
  has_many :answers, through: :results

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@(?:[A-Z0-9-]+\.)+[A-Z]+\z/i

  validates :name, presence: true,
    length: {maximum: Settings.validates.username.maxium}
  validates :emails, presence: true,
    length: {maximum: Settings.validates.emails.maxium},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :password, presence: true,
    length: {minimum: Settings.validates.password.minium}

  has_secure_password

  before_save :email_downcase

  private

  def email_downcase
    self.emails = emails.downcase
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category

  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :lessons, through: :results
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :logged_in_user, except: [:new, :create, :show]
  before_action :find_activity

  def show; end

  private

  def find_activity
    @activity = current_user.activity.find_by id: params[:id]
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, except: [:index, :create]
  before_action :logged_in_user, only: [:create, :new, :destroy]

  def index
    @category = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "success"
      redirect_to categories_path
    else
      render :new
    end
  end

  def show;  end

  def edit; end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".success"
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = t ".success", category: @category.name
    redirect_to categories_url
  end

  private
  def find_category
    @category = Category.find_by id: params[:id]
  end

  def category_params
    params.require(:category).permit :name
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :logged_in_user, except: [:new, :create, :show]

  def index
    @lessons = current_user.lessons
  end

  def show; end

  def find_lesson
    @lesson = current_user.lessons.includes(results: [:answer, word: :answers]).
      find_by_id params[:id]
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :logged_in_user, except: [:new, :create, :show]
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_url if logged_in?
  end

  def create
    user = User.find_by emails: params[:session][:emails].downcase
    if user
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = t ".problem-login"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:new, :create, :show]
  before_action :find_user, except: [:new, :index, :create]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate page: params[:page]
  end

  def new
    @user = User.new
  end

  def create
    user = User.new user_params
    if user.save
      log_in user
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @activity = user.activities.paginate(page: params[:page])
  end

  def edit; end

  def update
    if user.update_attributes user_params
      flash[:success] = t ".success"
      redirect_to user
    else
      render :edit
    end
  end

  def destroy
    user.destroy
    flash[:success] = t ".success", user: user.name
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit :name,
      :emails, :password, :password_confirmation
  end

  def logged_in_user
    return if logged_in?
    flash[:danger] = t ".warn"
    redirect_to login_url
  end

  def find_user
    user = User.find_by id: params[:id]
  end

  def correct_user
    return if @user.current_user? current_user
    redirect_to root_url
  end

  def admin_user
    return if current_user.admin?
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    page_title.empty? ? t(".title") : page_title + " | " + t("simple")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/helpers/user_helper.rb
module UsersHelper
  def gravatar_for user, size: 80
    gravatar_id = Digest::MD5.hexdigest user.emails.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: 80
    gravatar_id = Digest::MD5.hexdigest user.emails.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <%= t ".copy" %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar header" data-spy="affix"
  role="navigation" data-offset-top="130">
  <div class="container">
    <div class="navbar-header">
      <%= link_to root_path do %>
        <%= image_tag "logo2.png", class: "brand" %>
      <% end %>
    </div>
    <div class="navbar-right">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to t(".home"), root_path,
            class: "btn btn-lg sign-in-btn btn-white" %>
        </li>
        <% if logged_in? %>
          <li><%= link_to t(".user"), "#", class: "btn btn-lg sign-in-btn btn-white" %></li>
          <li class="dropdown">
            <%= link_to t(".acc"), "#",
             class: "dropdown-toggle btn btn-lg sign-in-btn btn-white",
              "data-toggle": "dropdown"%>
            <ul class="dropdown-menu">
              <li><%= link_to t(".prof"), "#" %></li>
              <li><%= link_to t(".setting"), "#" %></li>
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to t(".login"), login_path,
              class: "btn btn-lg sign-in-btn btn-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
    </div>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_activities.html.erb
<% if @activities_item.any? %>
  <ol class="activity">
    <%= render @activities_item %>
  </ol>
  <%= will_paginate @activities_item %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".sub" %> <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to relationships_path @user, type: "following" do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <p>
    	<%= t ".following" %>
    </p>
  <% end %>
  <%= link_to relationships_path @user, type: "followers" do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
  <p>
    <%= t ".followers" %>
  </p>
  <% end%>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user,
  size: 80), current_user %>

<h1><%= current_user.name %></h1>

<span><%= link_to t(".view"), current_user %></span>